baseURL = "https://labs.esokia.com"
title = "Esokia Labs"
languageCode = "fr-fr"
theme = "beautifulhugo"

[Params]
  subtitle = "Security advisories & research notes"
  mainSections = ["cve"]
#  logo = "img/esokia.png"

[permalinks]
  cve = "/cve/:slug/"

[[menu.main]]
  name = "CVE"
  url = "cve/"
  weight = 1